apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudmart # Глобально встановлюємо неймспейс для всіх файлів нижче

resources:
  - open-webui-pvc.yaml
  - open-webui-deployment.yaml
  - open-webui-service.yaml
  - open-webui-ingress.yaml
