apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - open-webui-pvc.yaml       # Додано новий файл
  - open-webui-deployment.yaml
  - open-webui-service.yaml
  - open-webui-ingress.yaml
