apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: cloudmart # Розміщуємо в одному неймспейсі з WebUI для простоти
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      nodeSelector:
        kubernetes.io/hostname: aorus # Завжди запускати там, де лежать файли
      containers:
      - name: ollama
        image: ollama/ollama:latest
        ports:
        - containerPort: 11434
        env:
        - name: OLLAMA_MODELS
          value: "/root/.ollama/models"
        volumeMounts:
        - name: host-ollama-root
          mountPath: /root/.ollama # Монтуємо в корінь робочої папки
      volumes:
      - name: host-ollama-root
        hostPath:
          path: /mnt/data/.ollama # Шлях до батьківської папки на хості
          type: Directory
