apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: open-webui
  namespace: cloudmart
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
  - host: openwebui.192.168.1.240.sslip.io # Ваш основний домен для AI
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: open-webui
            port:
              number: 80
