apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  namespace: cloudmart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:main # Остання версія
        ports:
        - containerPort: 8080
        env:
        - name: OLLAMA_BASE_URL
          value: "http://ollama-service.ollama.svc.cluster.local:11434" # Шлях до вашої Ollama
---
apiVersion: v1
kind: Service
metadata:
  name: open-webui-service
  namespace: cloudmart
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: open-webui
