apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-ingress.yaml
  - prometheus-rules.yaml
patches:
  - target:
      kind: Deployment
      name: monitoring-grafana
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          kubernetes.io/hostname: aorus
