apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#- ../../base/localstack
#- ../../base/ollama
resources:
- ../../base/namespace
- ../../base/ai-stack
- ../../base/agent-gateway
- ../../base/monitoring
- ../../base/cloudmart-backend
- ../../base/cloudmart-frontend
- ../../base/order-processor

images:
- name: cloudmart-backend
  newName: ghcr.io/igordems/cloudmart-backend
  newTag: latest
- name: cloudmart-frontend
  newName: ghcr.io/igordems/cloudmart-frontend
  newTag: latest
- name: ghcr.io/igordems/agent-gateway
  newName: ghcr.io/igordems/agent-gateway
  newTag: 16121b27860071d17d2f6f84ac061e5d0240fc4b
- name: order-processor
  newName: ghcr.io/igordems/cloudmart-order-processor
  newTag: latest
