apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/namespace
- ../../base/ollama
- ../../base/agent-gateway
- ../../base/monitoring
- ../../base/localstack
images:
- name: ghcr.io/igordems/agent-gateway
  newName: ghcr.io/igordems/agent-gateway
  newTag: 43d793aa1cbcdd52babeef4e61e3404eaeff00c4
