apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/namespace
- ../../base/ollama
- ../../base/agent-gateway
- ../../base/monitoring
- ../../base/localstack
images:
- name: ghcr.io/igordems/agent-gateway
  newName: ghcr.io/igordems/agent-gateway
  newTag: a24f603848fdd8b38493a992f3ac752931923342
