apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: cloudmart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      runtimeClassName: nvidia   # <--- ЦЕЙ РЯДОК ПРИМУСОВО ВМИКАЄ NVIDIA RUNTIME
      nodeSelector:
        kubernetes.io/hostname: aorus
      containers:
      - name: ollama
        image: ollama/ollama:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 11434
          protocol: TCP
        env:
        - name: OLLAMA_MODELS
          value: /root/.ollama/models
        - name: NVIDIA_VISIBLE_DEVICES
          value: "all"
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,utility"
        resources:
          limits:
            nvidia.com/gpu: "1"
          requests:
            nvidia.com/gpu: "1"
        volumeMounts:
        - mountPath: /root/.ollama
          name: host-ollama-root
      volumes:
      - hostPath:
          path: /mnt/data/.ollama
          type: Directory
        name: host-ollama-root
