apiVersion: v1
kind: Service
metadata:
  name: agent-gateway
  namespace: cloudmart
  labels:
    app: agent-gateway
    metrics: "true"
spec:
  selector:
    app: agent-gateway
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
