apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: agent-gateway
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - cloudmart
  selector:
    matchLabels:
      metrics: "true"
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
