apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudmart-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudmart-frontend
  template:
    metadata:
      labels:
        app: cloudmart-frontend
    spec:
      containers:
      - name: cloudmart-frontend
        image: ghcr.io/igordems/cloudmart-frontend:latest # Використовуйте повний шлях до іміджу
        ports:
        - containerPort: 3000
        # Додаємо команду запуску, щоб виправити поведінку додатка без перезбірки образу
        command: ["npx", "serve", "-s", "build", "-l", "3000"]
        env:
        - name: REACT_APP_API_URL
          value: "http://cloudmart-backend:8080"
