apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudmart-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudmart-frontend
  template:
    metadata:
      labels:
        app: cloudmart-frontend
    spec:
      containers:
      - name: cloudmart-frontend
        image: cloudmart-frontend
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: "http://cloudmart-backend:8080"
