apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudmart-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudmart-frontend
  template:
    metadata:
      labels:
        app: cloudmart-frontend
    spec:
      containers:
      - name: cloudmart-frontend
        image: ghcr.io/igordems/cloudmart-frontend:latest
        ports:
        - containerPort: 3000
        # Змінюємо "build" на "." оскільки файли лежать в /app
        command: ["npx", "serve", "-s", ".", "-l", "3000"]
        env:
        - name: REACT_APP_API_URL
          value: "http://api.192.168.1.240.sslip.io"
