apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudmart
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: ghcr.io/igordems/cloudmart-frontend
  newName: ffccddffe69273bb2054455be4f043d947c025ef
