apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudmart
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: ghcr.io/igordems/cloudmart-frontend
  newName: 6f782578143072fdf4e2a09155a01a6d6dd82002
