apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudmart
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: ghcr.io/igordems/cloudmart-frontend
  newName: 3badd220f7c9af32d091da579c2c900e7e63b0e6
