apiVersion: v1
kind: Service
metadata:
  name: cloudmart-frontend
  namespace: cloudmart
spec:
  selector:
    app: cloudmart-frontend
  ports:
    - protocol: TCP
      port: 3000       # Зовнішній порт сервісу (залишаємо як було)
      targetPort: 5001 # ПОРТ У КОНТЕЙНЕРІ (Змінюємо на 5001)
