apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace/
  - metallb/l2advertisement.yaml  # Змінено: вказано шлях до конкретного файлу
  - localstack/
  - ai-stack/
  - ollama/
  - cloudmart-backend/
  - cloudmart-frontend/
  - agent-gateway/
  - order-processor/
  - monitoring/
