apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cmls-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/IgorDems/CMLS.git
    targetRevision: main
    path: kubernetes/overlays/lab # Вказуємо на оверлей
  destination:
    server: https://kubernetes.default.svc
    # ВАЖЛИВО: Залишаємо порожнім, щоб Kustomize сам розкинув по неймспейсах
    namespace: ""
  syncPolicy:
    automated:
      prune: true     # Автоматично видалить дублікати та старі ресурси
      selfHeal: true  # Поверне стан, якщо ти щось зміниш вручну
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true # Допомагає чисто видаляти старі ReplicaSets
