apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudmart

resources:
- deployment.yaml
- service.yaml
- cloudmart-backend-ingress.yaml
images:
- name: ghcr.io/igordems/cloudmart-backend
  newName: ghcr.io/igordems/cloudmart-backend
  newTag: 19c394d7a1b0bcc8750e3e7406df4ecc91ef46f3
