apiVersion: v1
kind: Service
metadata:
  name: cloudmart-backend-app-service
  namespace: cloudmart
spec:
  type: ClusterIP
  selector:
    app: cloudmart-backend-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
