apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: default

spec:
  replicas: 1

  selector:
    matchLabels:
      app: localstack

  template:
    metadata:
      labels:
        app: localstack

    spec:
      containers:
        - name: localstack
          image: localstack/localstack:3.6
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 4566

          env:
            - name: SERVICES
              value: "dynamodb,sqs"

            - name: LS_LOG
              value: "info"

          volumeMounts:
            - name: localstack-init
              mountPath: /etc/localstack/init/ready.d/10-bootstrap.sh
              subPath: 10-bootstrap.sh

      volumes:
        - name: localstack-init
          configMap:
            name: localstack-init
            defaultMode: 0755
