name: Deploy CloudMart

on:
  push:
    branches: [ main ]
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Встановлюємо Kustomize правильно (Рішення помилки tar)
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2
        with:
          kustomize-version: "5.0.0"

      # Логіка оновлення образу (приклад для бекенду)
      - name: Update Backend Image
        run: |
          cd kubernetes/base/cloudmart-backend
          kustomize edit set image ghcr.io/igordems/cloudmart-backend=ghcr.io/igordems/cloudmart-backend:${{ github.sha }}

      # Логіка оновлення образу (приклад для фронтенду)
      - name: Update Frontend Image
        run: |
          cd kubernetes/base/cloudmart-frontend
          kustomize edit set image ghcr.io/igordems/cloudmart-frontend=${{ github.sha }}

      - name: Commit and Push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          
          # 1. Додаємо змінені файли маніфестів
          git add kubernetes/overlays/lab/kustomization.yaml
          
          # 2. Створюємо коміт, якщо є реальні зміни
          git commit -m "update agent-gateway image to $TAG" || echo "no changes"
          
          # 3. КРИТИЧНО: підтягуємо свіжі зміни з GitHub у режимі rebase
          git pull --rebase origin main
          
          # 4. Робимо безпечний push
          git push origin main
